version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

workflows:
  version: 2.1
  test_and_release:
    jobs:
      - test:
          name: "test-py36"
          version: "3.6"
          filters:  # required since `deploy` has tag filters
            tags:
              only: /.*/
            branches:
              ignore: gh-pages
      - test:
          name: "test-py37"
          version: "3.7"
          coverage: true
          filters:  # required since `deploy` has tag filters
            tags:
              only: /.*/
            branches:
              ignore: gh-pages
      - release:
          context:
            perdy-pypi
          filters:
            branches:  # ignore any commit on any branch by default
              ignore: /.*/
            tags:  # only act on version tags
              only: /v[0-9]+.*/
          requires:
            - test-py36
            - test-py37

jobs:
  test:
    parameters:
      version:
        type: string
        default: latest
      coverage:
        type: boolean
        default: false
    docker:
      - image: circleci/python:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo pip install clinner
            python make install
      - run:
          name: black
          command: python make black --check .
      - run:
          name: isort
          command: python make isort --check-only
      - run:
          name: flake8
          command: python make flake8
      - run:
          name: tests
          command: python make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - when:
          condition: << parameters.coverage >>
          steps:
            - run:
                name: codecov
                command: |
                  sudo pip install codecov
                  codecov -f test-results/coverage.xml
  release:
    docker:
      - image: perdy/circleci-python-builder:latest
    steps:
      - checkout
      - run:
          name: build & publish
          command: python make publish --build
